apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  ports:
  - port: 15672
    targetPort: 15672
    name: management
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app: rabbitmq
