// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecommendationAlgo.Repository.EFC;

#nullable disable

namespace RecommendationAlgo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240309120844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecommendationAlgo.Repository.Entities.VideoStats", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("VideoLength")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("VideoId");

                    b.ToTable("VideoStats");
                });

            modelBuilder.Entity("RecommendationAlgo.Repository.Entities.WatchHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(0);

                    b.Property<Guid>("VideoId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<bool>("FullyWatched")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Liked")
                        .HasColumnType("int");

                    b.Property<decimal>("WatchedTime")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("UserId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("RecommendationAlgo.Repository.Entities.WatchHistory", b =>
                {
                    b.HasOne("RecommendationAlgo.Repository.Entities.VideoStats", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
