apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: openvidstreamer/account:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONSUL_IP
              value: consul-service.default.svc.cluster.local 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: servicePort
              value: "8081"
            # CHANGE ALL ENV VARS BELLOW !!!!!  
            - name: StripeSecretKey
              value: "sk_test_51J4J7sk_test_51OpbAqLhuzbscNjkorQ4sXh7YsruJX0mYn3seAyim6fAaxZ2vnawug50BZknBpdbKCLOTNu1eT3pXWG84bDKLhab00kyOhVEW2"
            - name: StripeRedirectUrl
              value: "http://145.220.74.148:3000/paymentProcessed"
            - name: JwtSecret
              value: "rxio0SNqgU2yYEvOyZJ1greSMC75JBU0D6IxBZBxIXm+xzSr2ZZ+ZV/PHoV7sNYg7f9PCHulGu+QHG5qaSNpTQ=="
            - name: JwtExpiration
              value: "72"
