apiVersion: apps/v1
kind: Deployment
metadata:
  name: render-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: render
  template:
    metadata:
      labels:
        app: render
    spec:
      containers:
        - name: render
          image: openvidstreamer/render:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONSUL_IP
              value: consul-service.default.svc.cluster.local 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: servicePort
              value: "8081"
          volumeMounts:
            - mountPath: "/app/data"
              name: nfs-storage
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc

       
