apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: openvidstreamer/upload:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONSUL_IP
              value: consul-service.default.svc.cluster.local
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: servicePort
              value: "8081"
            - name: NFS_SERVER
              value: nfs-service
            - name: NFS_PATH
              value: "/exports"
          volumeMounts:
            - mountPath: "/app/data"
              name: nfs-storage
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
