apiVersion: apps/v1
kind: Deployment
metadata:
  name: videolib-db-deployment
spec:
  replicas: 1  # Ensure a single instance if it's a standalone database
  selector:
    matchLabels:
      app: videolib-db
  template:
    metadata:
      labels:
        app: videolib-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        - name: MYSQL_DATABASE
          value: "videolibdb"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: videolib-db-storage
          mountPath: /var/lib/mysql
        - name: mariadb-config
          mountPath: /etc/mysql/conf.d/custom.cnf
          subPath: custom.cnf
      volumes:
      - name: videolib-db-storage
        persistentVolumeClaim:
          claimName: videolib-db-pvc
      - name: mariadb-config
        configMap:
          name: mariadb-config
