#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8000
ENV ASPNETCORE_URLS=https://+:8000  

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["OpenVidStreamer.APIGateway/OpenVidStreamer.APIGateway.csproj", "OpenVidStreamer.APIGateway/"]
RUN dotnet restore "./OpenVidStreamer.APIGateway/./OpenVidStreamer.APIGateway.csproj"
COPY . .
WORKDIR "/src/OpenVidStreamer.APIGateway"
RUN dotnet build "./OpenVidStreamer.APIGateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./OpenVidStreamer.APIGateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
ENV ASPNETCORE_URLS=https://+:8000  
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OpenVidStreamer.APIGateway.dll"]