
const TermsAndConditionsText = () => {
    return (
        <div  className="space-y-6">
            <p>Welcome to OpenVidStreamer, a digital content sharing platform. By using our services,
                you agree to the following terms and conditions. Please read them carefully.</p>

            <h2>1. Data Collection and Use</h2>

            <h3>a. Data Collection</h3>
            <p>When you use OpenVidStreamer, you agree that we are authorized to collect data generated
                through your use of the platform. This includes, but is not limited to, personal
                information, content preferences, interaction data, and metadata related to the content
                you upload, view, and interact with.</p>

            <h3>b. Data Ownership</h3>
            <p>By agreeing to these terms, you acknowledge that OpenVidStreamer shall own all data
                generated by the platform. This ownership extends to any data collected based on your
                interaction with the platform.</p>

            <h3>c. Use of Data for Recommendations</h3>
            <p>We use the data collected to enhance your experience on the platform, including for the
                purpose of making personalized content recommendations. Our algorithms analyze your
                preferences, interactions, and other relevant data to provide you with tailored
                suggestions.</p>

            <h2>2. Resell and Sharing of Data</h2>

            <h3>a. Reselling Data</h3>
            <p>OpenVidStreamer reserves the right to share, sell, or otherwise distribute the data
                collected through the platform to third parties, in compliance with applicable laws and
                regulations regarding data privacy and protection.</p>

            <h3>b. Third-Party Access</h3>
            <p>We may allow third parties to access the data for purposes including, but not limited to,
                enhancing user experience, developing new features, and providing personalized
                advertisements.</p>

            <h2>3. User Consent</h2>

            <p>By using OpenVidStreamer, you explicitly consent to the collection, ownership, use, and
                sharing of your data as described in these terms and conditions. You also agree to
                update your preferences and consent as necessary to reflect any changes in your
                willingness to share personal information.</p>

            <h2>4. Limitation of Liability</h2>

            <p>You agree that OpenVidStreamer, its owners, employees, or any affiliated parties shall
                not be liable for any direct, indirect, incidental, special, consequential, or exemplary
                damages resulting from (i) your use or inability to use the platform; (ii) unauthorized
                access to or alteration of your data; or (iii) any other matter relating to the
                platform.</p>

            <h2>5. Indemnification</h2>

            <p>You agree to defend, indemnify, and hold harmless OpenVidStreamer and its affiliates from
                any claims, damages, obligations, losses, liabilities, costs, debt, and expenses arising
                from: (a) your use of and access to the platform; (b) your violation of any term of
                these terms and conditions; (c) your violation of any third-party right, including
                without limitation any copyright, privacy, or property right; or (d) any claim that your
                content caused damage to a third party.</p>

            <h2>6. Agreement</h2>

            <p>Your use of OpenVidStreamer signifies your agreement to these terms and conditions. If
                you do not agree with these terms, please do not use our services.</p>

        </div>
    );
};

export default TermsAndConditionsText;
