apiVersion: v1
kind: Service
metadata:
  name: video-streamer-service
spec:
  selector:
    app: video-streamer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP 
