apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationalgo-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: recommendationalgo
  template:
    metadata:
      labels:
        app: recommendationalgo
    spec:
      containers:
        - name: recommendationalgo
          image: <your-microservice-image>:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONSUL_IP
              value: consul-service.default.svc.cluster.local 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: servicePort
              value: "8081"
       
