name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    
    env:
      REPO_ROOT: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Updated to .NET 8

    - name: Install Chrome
      run: choco install googlechrome --ignore-checksums

    - name: Sleep for 10m
      run: Start-Sleep -s 600
      shell: powershell

    - name: Navigate to E2E Tests directory
      run: cd Backend/Tests/E2E.Tests

    - name: Restore .NET packages
      run: dotnet restore Backend/Tests/E2E.Tests/E2E.Tests.csproj

    - name: Restore .NET packages
      run: dotnet build Backend/Tests/E2E.Tests/E2E.Tests.csproj
      
    - name: Run E2E Tests
      run: dotnet test Backend/Tests/E2E.Tests/E2E.Tests.csproj

