name: .NET Build N Test RecommendationAlgo

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/RecommendationAlgo/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/RecommendationAlgo/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/RecommendationAlgo/RecommendationAlgo.csproj
    - name: Build
      run: dotnet build Backend/RecommendationAlgo/RecommendationAlgo.csproj --no-restore
    - name: Test
      run: dotnet test Backend/RecommendationAlgo/RecommendationAlgo.csproj --no-build --verbosity normal
