name: .NET Build N Test VideoLib

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/VideoStreamer/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/VideoStreamer/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/VideoStreamer/VideoStreamer.csproj
    - name: Build
      run: dotnet build Backend/VideoStreamer/VideoStreamer.csproj --no-restore
    - name: Test
      run: dotnet test Backend/VideoStreamer/VideoStreamer.csproj --no-build --verbosity normal
