name: ZAP Security Scan 

on:
  push:
    branches:
      - main

jobs:

  wait-for-deploy-finish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for  Deployment of Application
        run: sleep 640 


  zap_scan:
    needs: wait-for-deploy-finish
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.ZAPGHT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://145.220.74.148:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
