name: ZAP Security Scan 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  zap_scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.ZAPGHT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://react-app-xwjwz3lfdq-ez.a.run.app'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
